### ISSUE TITLE
Error upon startup

### ISSUE THREAD

**Issue by Boomer-1** [Sefiraat/CrystamaeHistoria#194]
hey Sefi - sorry I don't know what the issue is pointing to but I caught this in the log when loading my test server for 1.20

[12:07:39] [Server thread/INFO]: [CrystamaeHistoria] Loaded: 995 unique (block) stories.
[12:07:39] [Server thread/WARN]: [CrystamaeHistoria] Loaded class net.kyori.adventure.text.Component from AlchimiaVitae vDEV - 24 (git 6950e5d2) which is not a depend or softdepend of this plugin.
[12:07:39] [Server thread/ERROR]: [CrystamaeHistoria] Plugin CrystamaeHistoria vDEV - 81 (git 0c0efa95) has failed to register events for class io.github.sefiraat.crystamaehistoria.listeners.PhilosophersSprayListener because io/papermc/paper/event/block/BlockFailedDispenseEvent does not exist.
[12:07:39] [Server thread/ERROR]: Error occurred while enabling CrystamaeHistoria vDEV - 81 (git 0c0efa95) (Is it up to date?)
java.lang.NoClassDefFoundError: com/destroystokyo/paper/entity/ai/Goal
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1013) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:193) ~[spigot-api-1.20-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:104) ~[spigot-api-1.20-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-api-1.20-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at io.github.sefiraat.crystamaehistoria.magic.SpellType.<clinit>(SpellType.java:85) ~[?:?]
	at io.github.sefiraat.crystamaehistoria.managers.ConfigManager.loadConfig(ConfigManager.java:80) ~[?:?]
	at io.github.sefiraat.crystamaehistoria.CrystamaeHistoria.enable(CrystamaeHistoria.java:170) ~[?:?]
	at io.github.sefiraat.crystamaehistoria.infinitylib.core.AbstractAddon.onEnable(AbstractAddon.java:194) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.20-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.20-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.20-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:541) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3766-Spigot-81b9def-a345bb9]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:455) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3766-Spigot-81b9def-a345bb9]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:589) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3766-Spigot-81b9def-a345bb9]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3766-Spigot-81b9def-a345bb9]
	at net.minecraft.server
.dedicated.DedicatedServer.e(DedicatedServer.java:250) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3766-Spigot-81b9def-a345bb9]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:973) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3766-Spigot-81b9def-a345bb9]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3766-Spigot-81b9def-a345bb9]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.destroystokyo.paper.entity.ai.Goal
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147) ~[spigot-api-1.20-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-api-1.20-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]

**Comment by Boomer-1** [comment]
oh wait, i just realized this is the spigot jar Jeff sent me for testing slimefun. let me check, but my guess is it will go away with paper

**Comment by Boomer-1** [comment]
yeah, my bad. sorry for bugging ya.
