### ISSUE TITLE
X not finite > Fireball.java

### ISSUE THREAD

**Issue by Skizzles** [Sefiraat/CrystamaeHistoria#51]
[02:08:03 ERROR]: Could not pass event ProjectileHitEvent to CrystamaeHistoria vDEV - 17 (git 76ed6f7b)
java.lang.IllegalArgumentException: x not finite
        at org.bukkit.util.NumberConversions.checkFinite(NumberConversions.java:118) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.util.Vector.checkFinite(Vector.java:814) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.craftbukkit.v1_17_R1.entity.CraftEntity.setVelocity(CraftEntity.java:444) ~[patched_1.17.1.jar:git-Purpur-1428]
        at io.github.sefiraat.crystamaehistoria.utils.GeneralUtils.pushEntity(GeneralUtils.java:143) ~[CrystamaeHistoria - DEV 13 (git d853b).jar:?]
        at io.github.sefiraat.crystamaehistoria.utils.GeneralUtils.pushEntity(GeneralUtils.java:203) ~[CrystamaeHistoria - DEV 13 (git d853b).jar:?]
        at io.github.sefiraat.crystamaehistoria.utils.GeneralUtils.damageEntity(GeneralUtils.java:190) ~[CrystamaeHistoria - DEV 13 (git d853b).jar:?]
        at io.github.sefiraat.crystamaehistoria.magic.spells.tier1.Fireball.projectileHit(Fireball.java:41) ~[CrystamaeHistoria - DEV 13 (git d853b).jar:?]
        at io.github.sefiraat.crystamaehistoria.magic.CastInformation.runAffectEvent(CastInformation.java:82) ~[CrystamaeHistoria - DEV 13 (git d853b).jar:?]
        at io.github.sefiraat.crystamaehistoria.listeners.SpellEffectListener.onProjectileHit(SpellEffectListener.java:73) ~[CrystamaeHistoria - DEV 13 (git d853b).jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1482.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Purpur-1428]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callProjectileHitEvent(CraftEventFactory.java:1396) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.world.entity.projectile.Projectile.preOnHit(Projectile.java:213) ~[app:?]
        at net.minecraft.world.entity.projectile.AbstractHurtingProjectile.tick(AbstractHurtingProjectile.java:96) ~[app:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1204) ~[app:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$7(ServerLevel.java:802) ~[app:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:43) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:781) ~[app:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1652) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:528) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1507) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1300) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Purpur-1428]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]

**Comment by Sefiraat** [comment]
Can you provide some information around how/when/what/why/whale/who you casted this so I can dig deeper?

**Comment by marvjosh1** [comment]
@Sefiraat this happens if you hit an enderman with any spell that has a fireball in it c:

**Comment by Sefiraat** [comment]
> @Sefiraat this happens if you hit an enderman with any spell that has a fireball in it c:

Ah interesting, I'll do some testing and ship something during lunch. Thanks :)
