### ISSUE TITLE
Spawn Fiends cooldown and cost is broken

### ISSUE THREAD

**Issue by marvjosh1** [Sefiraat/CrystamaeHistoria#52]
The spell does not cost any mana, nor have a cooldown
https://youtu.be/w1JdT0-JTMw

**Comment by marvjosh1** [comment]
This is probably due to this error

[02:55:38 ERROR]: Could not pass event PlayerInteractEvent to CrystamaeHistoria vDEV - 17 (git 76ed6f7b)
java.lang.ClassCastException: class io.github.sefiraat.crystamaehistoria.magic.spells.spellobjects.MagicSummon cannot be cast to class org.bukkit.entity.Phantom (io.github.sefiraat.crystamaehistoria.magic.spells.spellobjects.MagicSummon is in unnamed module of loader 'CrystamaeHistoria - DEV 13 (git d853b).jar' @689e782a; org.bukkit.entity.Phantom is in unnamed module of loader 'app')
        at io.github.sefiraat.crystamaehistoria.magic.spells.tier1.SpawnFiends.cast(SpawnFiends.java:38) ~[CrystamaeHistoria - DEV 13 (git d853b).jar:?]
        at io.github.sefiraat.crystamaehistoria.magic.spells.core.Spell.castSpell(Spell.java:83) ~[CrystamaeHistoria - DEV 13 (git d853b).jar:?]
        at io.github.sefiraat.crystamaehistoria.magic.spells.core.InstancePlate.tryCastSpell(InstancePlate.java:79) ~[CrystamaeHistoria - DEV 13 (git d853b).jar:?]
        at io.github.sefiraat.crystamaehistoria.magic.spells.core.InstanceStave.tryCastSpell(InstanceStave.java:78) ~[CrystamaeHistoria - DEV 13 (git d853b).jar:?]
        at io.github.sefiraat.crystamaehistoria.listeners.SpellCastListener.onInteract(SpellCastListener.java:37) ~[CrystamaeHistoria - DEV 13 (git d853b).jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1480.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Purpur-1428]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:543) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:506) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:501) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:497) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItem(ServerGamePacketListenerImpl.java:1940) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:28) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.a(ServerboundUseItemPacket.java:8) ~[app:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1450) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1428) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1421) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:110) ~[app:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1560) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1300) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Purpur-1428]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
