### ISSUE TITLE
Tracer not stopping and generating an exception

### ISSUE THREAD

**Issue by marvjosh1** [Sefiraat/CrystamaeHistoria#53]
[03:14:39 WARN]: [CrystamaeHistoria] Task #426515 for CrystamaeHistoria vDEV - 17 (git 76ed6f7b) generated an exception
java.lang.IllegalArgumentException: Dust Options is null, something be bad: ARMOR_STAND
        at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[patched_1.17.1.jar:git-Purpur-1428]
        at io.github.sefiraat.crystamaehistoria.magic.spells.tier1.Tracer.onTick(Tracer.java:76) ~[CrystamaeHistoria - DEV 13 (git d853b).jar:?]
        at io.github.sefiraat.crystamaehistoria.magic.CastInformation.runTickEvent(CastInformation.java:100) ~[CrystamaeHistoria - DEV 13 (git d853b).jar:?]
        at io.github.sefiraat.crystamaehistoria.runnables.spells.SpellTickRunnable.run(SpellTickRunnable.java:26) ~[CrystamaeHistoria - DEV 13 (git d853b).jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1591) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:528) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1507) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1300) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Purpur-1428]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]

**Comment by Sefiraat** [comment]
Why WHY is ARMOR_STAND a living entity..... sigh. Despite this dumbness I should have a better workaround - ill add shortly 👍
