### ISSUE TITLE
i know u said max use is 5 but 13 is close enough 

### ISSUE THREAD

**Issue by RIPISDRAD** [Sefiraat/CrystamaeHistoria#8]
hey again and again :)
[09:06:02] [Server thread/INFO]: Evil_BlackHoles issued server command: /ch cast LOVE_POTION 1
[09:06:06] [Server thread/INFO]: Evil_BlackHoles issued server command: /ch cast LOVE_POTION 13
[09:06:06] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ch' in plugin CrystamaeHistoria vMODIFIED
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.17.1.jar:git-Paper-255]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Paper-255]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:838) ~[patched_1.17.1.jar:git-Paper-255]
	at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2248) ~[patched_1.17.1.jar:git-Paper-255]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2059) ~[patched_1.17.1.jar:git-Paper-255]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2040) ~[patched_1.17.1.jar:git-Paper-255]
	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46) ~[patched_1.17.1.jar:git-Paper-255]
	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6) ~[patched_1.17.1.jar:git-Paper-255]
	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56) ~[patched_1.17.1.jar:git-Paper-255]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-255]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149) ~[patched_1.17.1.jar:git-Paper-255]
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23) ~[patched_1.17.1.jar:git-Paper-255]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1418) ~[patched_1.17.1.jar:git-Paper-255]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Paper-255]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122) ~[patched_1.17.1.jar:git-Paper-255]
	at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1396) ~[patched_1.17.1.jar:git-Paper-255]
	at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1389) ~[patched_1.17.1.jar:git-Paper-255]
	at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132) ~[patched_1.17.1.jar:git-Paper-255]
	at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1367) ~[patched_1.17.1.jar:git-Paper-255]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1278) ~[patched_1.17.1.jar:git-Paper-255]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-255]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_17_R1.entity.CraftVillager cannot be cast to class org.bukkit.entity.Animals (org.bukkit.craftbukkit.v1_17_R1.entity.CraftVillager and org.bukkit.entity.Animals are in unnamed module of loader 'app')
	at io.github.sefiraat.crystamaehistoria.magic.spells.tier1.LovePotion.cast(LovePotion.java:32) ~[CrystamaeHistoria.vMODIFIED(2).jar:?]
	at io.github.sefiraat.crystamaehistoria.magic.spells.core.Spell.castSpell(Spell.java:90) ~[CrystamaeHistoria.vMODIFIED(2).jar:?]
	at io.github.sefiraat.crystamaehistoria.commands.TestSpell.execute(TestSpell.java:26) ~[CrystamaeHistoria.vMODIFIED(2).jar:?]
	at io.github.sefiraat.crystamaehistoria.infinitylib.commands.ParentCommand.execute(ParentCommand.java:62) ~[CrystamaeHistoria.vMODIFIED(2).jar:?]
	at io.github.sefiraat.crystamaehistoria.infinitylib.commands.AddonCommand.onCommand(AddonCommand.java:71) ~[CrystamaeHistoria.vMODIFIED(2).jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.1.jar:git-Paper-255]
	... 21 more
[09:06:37] [Server thread/INFO]: Evil_BlackHoles issued server command: /ch cast KNOWLEDGE_SHARE 1
[09:06:37] [Server thread/WARN]: [CrystamaeHistoria] Task #56516 for CrystamaeHistoria vMODIFIED generated an exception
java.lang.NoSuchFieldError: DRIPPING_DRIPSTONE
	at io.github.sefiraat.crystamaehistoria.magic.spells.tier1.KnowledgeShare.onTick(KnowledgeShare.java:49) ~[CrystamaeHistoria.vMODIFIED(2).jar:?]
	at io.github.sefiraat.crystamaehistoria.magic.CastInformation.runTickEvent(CastInformation.java:91) ~[CrystamaeHistoria.vMODIFIED(2).jar:?]
	at io.github.sefiraat.crystamaehistoria.runnables.spells.SpellTick.run(SpellTick.java:26) ~[CrystamaeHistoria.vMODIFIED(2).jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-255]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-255]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1559) ~[patched_1.17.1.jar:git-Paper-255]
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:479) ~[patched_1.17.1.jar:git-Paper-255]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1475) ~[patched_1.17.1.jar:git-Paper-255]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1274) ~[patched_1.17.1.jar:git-Paper-255]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-255]
	at java.lang.Thread.run(Unknown Source) [?:?]
[09:06:37] [Server thread/WARN]: [CrystamaeHistoria] Task #56516 for CrystamaeHistoria vMODIFIED generated an exception
java.lang.NoSuchFieldError: DRIPPING_DRIPSTONE
	at io.github.sefiraat.crystamaehistoria.magic.spells.tier1.KnowledgeShare.onTick(KnowledgeShare.java:49) ~[CrystamaeHistoria.vMODIFIED(2).jar:?]
	at io.github.sefiraat.crystamaehistoria.magic.CastInformation.runTickEvent(CastInformation.java:91) ~[CrystamaeHistoria.vMODIFIED(2).jar:?]
	at io.github.sefiraat.crystamaehistoria.runnables.spells.SpellTick.run(SpellTick.java:26) ~[CrystamaeHistoria.vMODIFIED(2).jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-255]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-255]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1559) ~[patched_1.17.1.jar:git-Paper-255]
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:479) ~[patched_1.17.1.jar:git-Paper-255]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1475) ~[patched_1.17.1.jar:git-Paper-255]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1274) ~[patched_1.17.1.jar:git-Paper-255]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-255]
	at java.lang.Thread.run(Unknown Source) [?:?]
[09:06:37] [Server thread/WARN]: [CrystamaeHistoria] Task #56516 for CrystamaeHistoria vMODIFIED generated an exception
java.lang.NoSuchFieldError: DRIPPING_DRIPSTONE
	at io.github.sefiraat.crystamaehistoria.magic.spells.tier1.KnowledgeShare.onTick(KnowledgeShare.java:49) ~[CrystamaeHistoria.vMODIFIED(2).jar:?]
	at io.github.sefiraat.crystamaehistoria.magic.CastInformation.runTickEvent(CastInformation.java:91) ~[CrystamaeHistoria.vMODIFIED(2).jar:?]
	at io.github.sefiraat.crystamaehistoria.runnables.spells.SpellTick.run(SpellTick.java:26) ~[CrystamaeHistoria.vMODIFIED(2).jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-255]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-255]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1559) ~[patched_1.17.1.jar:git-Paper-255]
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:479) ~[patched_1.17.1.jar:git-Paper-255]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1475) ~[patched_1.17.1.jar:git-Paper-255]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1274) ~[patched_1.17.1.jar:git-Paper-255]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-255]
	at java.lang.Thread.run(Unknown Source) [?:?]
[09:06:37] [Server thread/WARN]: [CrystamaeHistoria] Task #56516 for CrystamaeHistoria vMODIFIED generated an exception
java.lang.NoSuchFieldError: DRIPPING_DRIPSTONE
	at io.github.sefiraat.crystamaehistoria.magic.spells.tier1.KnowledgeShare.onTick(KnowledgeShare.java:49) ~[CrystamaeHistoria.vMODIFIED(2).jar:?]
	at io.github.sefiraat.crystamaehistoria.magic.CastInformation.runTickEvent(CastInformation.java:91) ~[CrystamaeHistoria.vMODIFIED(2).jar:?]
	at io.github.sefiraat.crystamaehistoria.runnables.spells.SpellTick.run(SpellTick.java:26) ~[CrystamaeHistoria.vMODIFIED(2).jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-255]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-255]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1559) ~[patched_1.17.1.jar:git-Paper-255]
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:479) ~[patched_1.17.1.jar:git-Paper-255]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1475) ~[patched_1.17.1.jar:git-Paper-255]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1274) ~[patched_1.17.1.jar:git-Paper-255]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-255]
	at java.lang.Thread.run(Unknown Source) [?:?]
[09:06:37] [Server thread/WARN]: [CrystamaeHistoria] Task #56516 for CrystamaeHistoria vMODIFIED generated an exception
java.lang.NoSuchFieldError: DRIPPING_DRIPSTONE
	at io.github.sefiraat.crystamaehistoria.magic.spells.tier1.KnowledgeShare.onTick(KnowledgeShare.java:49) ~[CrystamaeHistoria.vMODIFIED(2).jar:?]
	at io.github.sefiraat.crystamaehistoria.magic.CastInformation.runTickEvent(CastInformation.java:91) ~[CrystamaeHistoria.vMODIFIED(2).jar:?]
	at io.github.sefiraat.crystamaehistoria.runnables.spells.SpellTick.run(SpellTick.java:26) ~[CrystamaeHistoria.vMODIFIED(2).jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-255]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-255]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1559) ~[patched_1.17.1.jar:git-Paper-255]
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:479) ~[patched_1.17.1.jar:git-Paper-255]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1475) ~[patched_1.17.1.jar:git-Paper-255]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1274) ~[patched_1.17.1.jar:git-Paper-255]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-255]
	at java.lang.Thread.run(Unknown Source) [?:?]
[09:06:37] [Server thread/WARN]: [CrystamaeHistoria] Task #56516 for CrystamaeHistoria vMODIFIED generated an exception
java.lang.NoSuchFieldError: DRIPPING_DRIPSTONE
	at io.github.sefiraat.crystamaehistoria.magic.spells.tier1.KnowledgeShare.onTick(KnowledgeShare.java:49) ~[CrystamaeHistoria.vMODIFIED(2).jar:?]
	at io.github.sefiraat.crystamaehistoria.magic.CastInformation.runTickEvent(CastInformation.java:91) ~[CrystamaeHistoria.vMODIFIED(2).jar:?]
	at io.github.sefiraat.crystamaehistoria.runnables.spells.SpellTick.run(SpellTick.java:26) ~[CrystamaeHistoria.vMODIFIED(2).jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-255]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-255]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1559) ~[patched_1.17.1.jar:git-Paper-255]
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:479) ~[patched_1.17.1.jar:git-Paper-255]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1475) ~[patched_1.17.1.jar:git-Paper-255]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1274) ~[patched_1.17.1.jar:git-Paper-255]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-255]
	at java.lang.Thread.run(Unknown Source) [?:?]

**Comment by Sefiraat** [comment]
Again, any errors due to numbers over 5 will not be checked lol ;)
